//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Partner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagesToSubcRibtion_tbl
    {
        public string subcId { get; set; }
        public string packId { get; set; }
        public Nullable<int> usingMinitues { get; set; }
    
        public virtual Package_tbl Package_tbl { get; set; }
        public virtual Subcribtion Subcribtion { get; set; }
    }
}
